package com.tgneventos.pojo;

import com.google.firebase.firestore.Exclude;
import com.google.firebase.firestore.PropertyName;

import java.io.Serializable;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;

public final class Event implements Serializable
{
    // Fields
    @Exclude private String _id; // Auto-generated by firebase, meant to only be used as a document getter
    private String _title;
    private String _category;
    private LocalDateTime _dateTime;
    private String _location;
    private String _ubication;
    private String _web;
    private double _price;
    private String _description;
    private String _imageUrl;

    // Constructors
    public Event() {}

    public Event(String _id, String _title, String _category, LocalDateTime _dateTime, String _location, String _ubication, String _web, double _price, String _description, String _imageUrl) {
        this._id = _id;
        this._title = _title;
        this._category = _category;
        this._dateTime = _dateTime;
        this._location = _location;
        this._ubication = _ubication;
        this._web = _web;
        this._price = _price;
        this._description = _description;
        this._imageUrl = _imageUrl;
    }

    // Getters & setters
    public String getTitle() { return _title; }
    public void setTitle(String title) { _title = title; }

    public String getCategory() { return _category; }
    public void setCategory(String category) { _category = category; }

    @Exclude public LocalDateTime getDateTime() { return _dateTime; }
    @Exclude public LocalDate getDate() { return _dateTime.toLocalDate(); }
    @Exclude public LocalTime getTime() { return _dateTime.toLocalTime(); }
    @Exclude public void setDateTime(LocalDateTime dateTime) { _dateTime = dateTime; }

    public String getLocation() { return _location; }
    public void setLocation(String location) { _location = location; }

    public double getPrice() { return _price; }
    public void setPrice(double price) { _price = price; }

    public String getDescription() { return _description; }
    public void setDescription(String description) { _description = description; }

    public String getImageUrl() { return _imageUrl; }
    public void setImageUrl(String imageUrl) { _imageUrl = imageUrl; }

    public String get_web() {
        return _web;
    }

    public void set_web(String _web) {
        this._web = _web;
    }

    public String get_ubication() {
        return _ubication;
    }

    public void set_ubication(String _ubication) {
        this._ubication = _ubication;
    }

    public String getId() { return _id; }
    public void setId(String id) { _id = id; }

    // Firestore specific getters and setters
    @PropertyName("dateTime")
    public String getDateTimeString() { return _dateTime.format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm")); }

    @PropertyName("dateTime")
    public void setDateTimeString(String formattedDate) { _dateTime = LocalDateTime.parse(formattedDate, DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm")); }
}
